/* Generated from # Blocks-4.1.0.txt on 2006-03-26 16:09:45 */

#define bbCPGUNICODE_BLOCK_BASIC_LATIN 0
#define bbCPGUNICODE_BLOCK_LATIN_1_SUPPLEMENT 1
#define bbCPGUNICODE_BLOCK_LATIN_EXTENDED_A 2
#define bbCPGUNICODE_BLOCK_LATIN_EXTENDED_B 3
#define bbCPGUNICODE_BLOCK_IPA_EXTENSIONS 4
#define bbCPGUNICODE_BLOCK_SPACING_MODIFIER_LETTERS 5
#define bbCPGUNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS 6
#define bbCPGUNICODE_BLOCK_GREEK_AND_COPTIC 7
#define bbCPGUNICODE_BLOCK_CYRILLIC 8
#define bbCPGUNICODE_BLOCK_CYRILLIC_SUPPLEMENT 9
#define bbCPGUNICODE_BLOCK_ARMENIAN 10
#define bbCPGUNICODE_BLOCK_HEBREW 11
#define bbCPGUNICODE_BLOCK_ARABIC 12
#define bbCPGUNICODE_BLOCK_SYRIAC 13
#define bbCPGUNICODE_BLOCK_ARABIC_SUPPLEMENT 14
#define bbCPGUNICODE_BLOCK_THAANA 15
#define bbCPGUNICODE_BLOCK_DEVANAGARI 17
#define bbCPGUNICODE_BLOCK_BENGALI 18
#define bbCPGUNICODE_BLOCK_GURMUKHI 19
#define bbCPGUNICODE_BLOCK_GUJARATI 20
#define bbCPGUNICODE_BLOCK_ORIYA 21
#define bbCPGUNICODE_BLOCK_TAMIL 22
#define bbCPGUNICODE_BLOCK_TELUGU 23
#define bbCPGUNICODE_BLOCK_KANNADA 24
#define bbCPGUNICODE_BLOCK_MALAYALAM 25
#define bbCPGUNICODE_BLOCK_SINHALA 26
#define bbCPGUNICODE_BLOCK_THAI 27
#define bbCPGUNICODE_BLOCK_LAO 28
#define bbCPGUNICODE_BLOCK_TIBETAN 29
#define bbCPGUNICODE_BLOCK_MYANMAR 30
#define bbCPGUNICODE_BLOCK_GEORGIAN 31
#define bbCPGUNICODE_BLOCK_HANGUL_JAMO 32
#define bbCPGUNICODE_BLOCK_ETHIOPIC 33
#define bbCPGUNICODE_BLOCK_ETHIOPIC_SUPPLEMENT 34
#define bbCPGUNICODE_BLOCK_CHEROKEE 35
#define bbCPGUNICODE_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS 36
#define bbCPGUNICODE_BLOCK_OGHAM 37
#define bbCPGUNICODE_BLOCK_RUNIC 38
#define bbCPGUNICODE_BLOCK_TAGALOG 39
#define bbCPGUNICODE_BLOCK_HANUNOO 40
#define bbCPGUNICODE_BLOCK_BUHID 41
#define bbCPGUNICODE_BLOCK_TAGBANWA 42
#define bbCPGUNICODE_BLOCK_KHMER 43
#define bbCPGUNICODE_BLOCK_MONGOLIAN 44
#define bbCPGUNICODE_BLOCK_LIMBU 46
#define bbCPGUNICODE_BLOCK_TAI_LE 47
#define bbCPGUNICODE_BLOCK_NEW_TAI_LUE 48
#define bbCPGUNICODE_BLOCK_KHMER_SYMBOLS 49
#define bbCPGUNICODE_BLOCK_BUGINESE 50
#define bbCPGUNICODE_BLOCK_PHONETIC_EXTENSIONS 52
#define bbCPGUNICODE_BLOCK_PHONETIC_EXTENSIONS_SUPPLEMENT 53
#define bbCPGUNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT 54
#define bbCPGUNICODE_BLOCK_LATIN_EXTENDED_ADDITIONAL 55
#define bbCPGUNICODE_BLOCK_GREEK_EXTENDED 56
#define bbCPGUNICODE_BLOCK_GENERAL_PUNCTUATION 57
#define bbCPGUNICODE_BLOCK_SUPERSCRIPTS_AND_SUBSCRIPTS 58
#define bbCPGUNICODE_BLOCK_CURRENCY_SYMBOLS 59
#define bbCPGUNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS 60
#define bbCPGUNICODE_BLOCK_LETTERLIKE_SYMBOLS 61
#define bbCPGUNICODE_BLOCK_NUMBER_FORMS 62
#define bbCPGUNICODE_BLOCK_ARROWS 63
#define bbCPGUNICODE_BLOCK_MATHEMATICAL_OPERATORS 64
#define bbCPGUNICODE_BLOCK_MISCELLANEOUS_TECHNICAL 65
#define bbCPGUNICODE_BLOCK_CONTROL_PICTURES 66
#define bbCPGUNICODE_BLOCK_OPTICAL_CHARACTER_RECOGNITION 67
#define bbCPGUNICODE_BLOCK_ENCLOSED_ALPHANUMERICS 68
#define bbCPGUNICODE_BLOCK_BOX_DRAWING 69
#define bbCPGUNICODE_BLOCK_BLOCK_ELEMENTS 70
#define bbCPGUNICODE_BLOCK_GEOMETRIC_SHAPES 71
#define bbCPGUNICODE_BLOCK_MISCELLANEOUS_SYMBOLS 72
#define bbCPGUNICODE_BLOCK_DINGBATS 73
#define bbCPGUNICODE_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A 74
#define bbCPGUNICODE_BLOCK_SUPPLEMENTAL_ARROWS_A 75
#define bbCPGUNICODE_BLOCK_BRAILLE_PATTERNS 76
#define bbCPGUNICODE_BLOCK_SUPPLEMENTAL_ARROWS_B 77
#define bbCPGUNICODE_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B 78
#define bbCPGUNICODE_BLOCK_SUPPLEMENTAL_MATHEMATICAL_OPERATORS 79
#define bbCPGUNICODE_BLOCK_MISCELLANEOUS_SYMBOLS_AND_ARROWS 80
#define bbCPGUNICODE_BLOCK_GLAGOLITIC 81
#define bbCPGUNICODE_BLOCK_COPTIC 83
#define bbCPGUNICODE_BLOCK_GEORGIAN_SUPPLEMENT 84
#define bbCPGUNICODE_BLOCK_TIFINAGH 85
#define bbCPGUNICODE_BLOCK_ETHIOPIC_EXTENDED 86
#define bbCPGUNICODE_BLOCK_SUPPLEMENTAL_PUNCTUATION 88
#define bbCPGUNICODE_BLOCK_CJK_RADICALS_SUPPLEMENT 89
#define bbCPGUNICODE_BLOCK_KANGXI_RADICALS 90
#define bbCPGUNICODE_BLOCK_IDEOGRAPHIC_DESCRIPTION_CHARACTERS 92
#define bbCPGUNICODE_BLOCK_CJK_SYMBOLS_AND_PUNCTUATION 93
#define bbCPGUNICODE_BLOCK_HIRAGANA 94
#define bbCPGUNICODE_BLOCK_KATAKANA 95
#define bbCPGUNICODE_BLOCK_BOPOMOFO 96
#define bbCPGUNICODE_BLOCK_HANGUL_COMPATIBILITY_JAMO 97
#define bbCPGUNICODE_BLOCK_KANBUN 98
#define bbCPGUNICODE_BLOCK_BOPOMOFO_EXTENDED 99
#define bbCPGUNICODE_BLOCK_CJK_STROKES 100
#define bbCPGUNICODE_BLOCK_KATAKANA_PHONETIC_EXTENSIONS 101
#define bbCPGUNICODE_BLOCK_ENCLOSED_CJK_LETTERS_AND_MONTHS 102
#define bbCPGUNICODE_BLOCK_CJK_COMPATIBILITY 103
#define bbCPGUNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A 104
#define bbCPGUNICODE_BLOCK_YIJING_HEXAGRAM_SYMBOLS 105
#define bbCPGUNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS 106
#define bbCPGUNICODE_BLOCK_YI_SYLLABLES 107
#define bbCPGUNICODE_BLOCK_YI_RADICALS 108
#define bbCPGUNICODE_BLOCK_MODIFIER_TONE_LETTERS 110
#define bbCPGUNICODE_BLOCK_SYLOTI_NAGRI 112
#define bbCPGUNICODE_BLOCK_HANGUL_SYLLABLES 114
#define bbCPGUNICODE_BLOCK_HIGH_SURROGATES 116
#define bbCPGUNICODE_BLOCK_HIGH_PRIVATE_USE_SURROGATES 117
#define bbCPGUNICODE_BLOCK_LOW_SURROGATES 118
#define bbCPGUNICODE_BLOCK_PRIVATE_USE_AREA 119
#define bbCPGUNICODE_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS 120
#define bbCPGUNICODE_BLOCK_ALPHABETIC_PRESENTATION_FORMS 121
#define bbCPGUNICODE_BLOCK_ARABIC_PRESENTATION_FORMS_A 122
#define bbCPGUNICODE_BLOCK_VARIATION_SELECTORS 123
#define bbCPGUNICODE_BLOCK_VERTICAL_FORMS 124
#define bbCPGUNICODE_BLOCK_COMBINING_HALF_MARKS 125
#define bbCPGUNICODE_BLOCK_CJK_COMPATIBILITY_FORMS 126
#define bbCPGUNICODE_BLOCK_SMALL_FORM_VARIANTS 127
#define bbCPGUNICODE_BLOCK_ARABIC_PRESENTATION_FORMS_B 128
#define bbCPGUNICODE_BLOCK_HALFWIDTH_AND_FULLWIDTH_FORMS 129
#define bbCPGUNICODE_BLOCK_SPECIALS 130
#define bbCPGUNICODE_BLOCK_LINEAR_B_SYLLABARY 131
#define bbCPGUNICODE_BLOCK_LINEAR_B_IDEOGRAMS 132
#define bbCPGUNICODE_BLOCK_AEGEAN_NUMBERS 133
#define bbCPGUNICODE_BLOCK_ANCIENT_GREEK_NUMBERS 134
#define bbCPGUNICODE_BLOCK_OLD_ITALIC 136
#define bbCPGUNICODE_BLOCK_GOTHIC 137
#define bbCPGUNICODE_BLOCK_UGARITIC 139
#define bbCPGUNICODE_BLOCK_OLD_PERSIAN 140
#define bbCPGUNICODE_BLOCK_DESERET 142
#define bbCPGUNICODE_BLOCK_SHAVIAN 143
#define bbCPGUNICODE_BLOCK_OSMANYA 144
#define bbCPGUNICODE_BLOCK_CYPRIOT_SYLLABARY 146
#define bbCPGUNICODE_BLOCK_KHAROSHTHI 148
#define bbCPGUNICODE_BLOCK_BYZANTINE_MUSICAL_SYMBOLS 150
#define bbCPGUNICODE_BLOCK_MUSICAL_SYMBOLS 151
#define bbCPGUNICODE_BLOCK_ANCIENT_GREEK_MUSICAL_NOTATION 152
#define bbCPGUNICODE_BLOCK_TAI_XUAN_JING_SYMBOLS 154
#define bbCPGUNICODE_BLOCK_MATHEMATICAL_ALPHANUMERIC_SYMBOLS 156
#define bbCPGUNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B 158
#define bbCPGUNICODE_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT 160
#define bbCPGUNICODE_BLOCK_TAGS 162
#define bbCPGUNICODE_BLOCK_VARIATION_SELECTORS_SUPPLEMENT 164
#define bbCPGUNICODE_BLOCK_SUPPLEMENTARY_PRIVATE_USE_AREA_A 166
#define bbCPGUNICODE_BLOCK_SUPPLEMENTARY_PRIVATE_USE_AREA_B 167
#define bbCPGUNICODE_BLOCKCOUNT 168

#define bbCPGUNICODE_BLOCKNAMES \
bbT("Basic Latin"),\
bbT("Latin-1 Supplement"),\
bbT("Latin Extended-A"),\
bbT("Latin Extended-B"),\
bbT("IPA Extensions"),\
bbT("Spacing Modifier Letters"),\
bbT("Combining Diacritical Marks"),\
bbT("Greek and Coptic"),\
bbT("Cyrillic"),\
bbT("Cyrillic Supplement"),\
bbT("Armenian"),\
bbT("Hebrew"),\
bbT("Arabic"),\
bbT("Syriac"),\
bbT("Arabic Supplement"),\
bbT("Thaana"),\
NULL,\
bbT("Devanagari"),\
bbT("Bengali"),\
bbT("Gurmukhi"),\
bbT("Gujarati"),\
bbT("Oriya"),\
bbT("Tamil"),\
bbT("Telugu"),\
bbT("Kannada"),\
bbT("Malayalam"),\
bbT("Sinhala"),\
bbT("Thai"),\
bbT("Lao"),\
bbT("Tibetan"),\
bbT("Myanmar"),\
bbT("Georgian"),\
bbT("Hangul Jamo"),\
bbT("Ethiopic"),\
bbT("Ethiopic Supplement"),\
bbT("Cherokee"),\
bbT("Unified Canadian Aboriginal Syllabics"),\
bbT("Ogham"),\
bbT("Runic"),\
bbT("Tagalog"),\
bbT("Hanunoo"),\
bbT("Buhid"),\
bbT("Tagbanwa"),\
bbT("Khmer"),\
bbT("Mongolian"),\
NULL,\
bbT("Limbu"),\
bbT("Tai Le"),\
bbT("New Tai Lue"),\
bbT("Khmer Symbols"),\
bbT("Buginese"),\
NULL,\
bbT("Phonetic Extensions"),\
bbT("Phonetic Extensions Supplement"),\
bbT("Combining Diacritical Marks Supplement"),\
bbT("Latin Extended Additional"),\
bbT("Greek Extended"),\
bbT("General Punctuation"),\
bbT("Superscripts and Subscripts"),\
bbT("Currency Symbols"),\
bbT("Combining Diacritical Marks for Symbols"),\
bbT("Letterlike Symbols"),\
bbT("Number Forms"),\
bbT("Arrows"),\
bbT("Mathematical Operators"),\
bbT("Miscellaneous Technical"),\
bbT("Control Pictures"),\
bbT("Optical Character Recognition"),\
bbT("Enclosed Alphanumerics"),\
bbT("Box Drawing"),\
bbT("Block Elements"),\
bbT("Geometric Shapes"),\
bbT("Miscellaneous Symbols"),\
bbT("Dingbats"),\
bbT("Miscellaneous Mathematical Symbols-A"),\
bbT("Supplemental Arrows-A"),\
bbT("Braille Patterns"),\
bbT("Supplemental Arrows-B"),\
bbT("Miscellaneous Mathematical Symbols-B"),\
bbT("Supplemental Mathematical Operators"),\
bbT("Miscellaneous Symbols and Arrows"),\
bbT("Glagolitic"),\
NULL,\
bbT("Coptic"),\
bbT("Georgian Supplement"),\
bbT("Tifinagh"),\
bbT("Ethiopic Extended"),\
NULL,\
bbT("Supplemental Punctuation"),\
bbT("CJK Radicals Supplement"),\
bbT("Kangxi Radicals"),\
NULL,\
bbT("Ideographic Description Characters"),\
bbT("CJK Symbols and Punctuation"),\
bbT("Hiragana"),\
bbT("Katakana"),\
bbT("Bopomofo"),\
bbT("Hangul Compatibility Jamo"),\
bbT("Kanbun"),\
bbT("Bopomofo Extended"),\
bbT("CJK Strokes"),\
bbT("Katakana Phonetic Extensions"),\
bbT("Enclosed CJK Letters and Months"),\
bbT("CJK Compatibility"),\
bbT("CJK Unified Ideographs Extension A"),\
bbT("Yijing Hexagram Symbols"),\
bbT("CJK Unified Ideographs"),\
bbT("Yi Syllables"),\
bbT("Yi Radicals"),\
NULL,\
bbT("Modifier Tone Letters"),\
NULL,\
bbT("Syloti Nagri"),\
NULL,\
bbT("Hangul Syllables"),\
NULL,\
bbT("High Surrogates"),\
bbT("High Private Use Surrogates"),\
bbT("Low Surrogates"),\
bbT("Private Use Area"),\
bbT("CJK Compatibility Ideographs"),\
bbT("Alphabetic Presentation Forms"),\
bbT("Arabic Presentation Forms-A"),\
bbT("Variation Selectors"),\
bbT("Vertical Forms"),\
bbT("Combining Half Marks"),\
bbT("CJK Compatibility Forms"),\
bbT("Small Form Variants"),\
bbT("Arabic Presentation Forms-B"),\
bbT("Halfwidth and Fullwidth Forms"),\
bbT("Specials"),\
bbT("Linear B Syllabary"),\
bbT("Linear B Ideograms"),\
bbT("Aegean Numbers"),\
bbT("Ancient Greek Numbers"),\
NULL,\
bbT("Old Italic"),\
bbT("Gothic"),\
NULL,\
bbT("Ugaritic"),\
bbT("Old Persian"),\
NULL,\
bbT("Deseret"),\
bbT("Shavian"),\
bbT("Osmanya"),\
NULL,\
bbT("Cypriot Syllabary"),\
NULL,\
bbT("Kharoshthi"),\
NULL,\
bbT("Byzantine Musical Symbols"),\
bbT("Musical Symbols"),\
bbT("Ancient Greek Musical Notation"),\
NULL,\
bbT("Tai Xuan Jing Symbols"),\
NULL,\
bbT("Mathematical Alphanumeric Symbols"),\
NULL,\
bbT("CJK Unified Ideographs Extension B"),\
NULL,\
bbT("CJK Compatibility Ideographs Supplement"),\
NULL,\
bbT("Tags"),\
NULL,\
bbT("Variation Selectors Supplement"),\
NULL,\
bbT("Supplementary Private Use Area-A"),\
bbT("Supplementary Private Use Area-B")
#define bbCPGUNICODE_BLOCKNAME_MAXLEN 39

#define bbCPGUNICODE_BLOCKINDEX \
0x0000U,0x0008U,0x0010U,0x0018U,0x0025U,0x002BU,0x0030U,0x0037U,\
0x0040U,0x0050U,0x0053U,0x0059U,0x0060U,0x0070U,0x0075U,0x0078U,\
0x007CU,0x0090U,0x0098U,0x00A0U,0x00A8U,0x00B0U,0x00B8U,0x00C0U,\
0x00C8U,0x00D0U,0x00D8U,0x00E0U,0x00E8U,0x00F0U,0x0100U,0x010AU,\
0x0110U,0x0120U,0x0138U,0x013AU,0x0140U,0x0168U,0x016AU,0x0170U,\
0x0172U,0x0174U,0x0176U,0x0178U,0x0180U,0x018BU,0x0190U,0x0195U,\
0x0198U,0x019EU,0x01A0U,0x01A2U,0x01D0U,0x01D8U,0x01DCU,0x01E0U,\
0x01F0U,0x0200U,0x0207U,0x020AU,0x020DU,0x0210U,0x0215U,0x0219U,\
0x0220U,0x0230U,0x0240U,0x0244U,0x0246U,0x0250U,0x0258U,0x025AU,\
0x0260U,0x0270U,0x027CU,0x027FU,0x0280U,0x0290U,0x0298U,0x02A0U,\
0x02B0U,0x02C0U,0x02C6U,0x02C8U,0x02D0U,0x02D3U,0x02D8U,0x02DEU,\
0x02E0U,0x02E8U,0x02F0U,0x02FEU,0x02FFU,0x0300U,0x0304U,0x030AU,\
0x0310U,0x0313U,0x0319U,0x031AU,0x031CU,0x031FU,0x0320U,0x0330U,\
0x0340U,0x04DCU,0x04E0U,0x0A00U,0x0A49U,0x0A4DU,0x0A70U,0x0A72U,\
0x0A80U,0x0A83U,0x0AC0U,0x0D7BU,0x0D80U,0x0DB8U,0x0DC0U,0x0E00U,\
0x0F90U,0x0FB0U,0x0FB5U,0x0FE0U,0x0FE1U,0x0FE2U,0x0FE3U,0x0FE5U,\
0x0FE7U,0x0FF0U,0x0FFFU,0x1000U,0x1008U,0x1010U,0x1014U,0x1019U,\
0x1030U,0x1033U,0x1035U,0x1038U,0x103AU,0x103EU,0x1040U,0x1045U,\
0x1048U,0x104BU,0x1080U,0x1084U,0x10A0U,0x10A6U,0x1D00U,0x1D10U,\
0x1D20U,0x1D25U,0x1D30U,0x1D36U,0x1D40U,0x1D80U,0x2000U,0x2A6EU,\
0x2F80U,0x2FA2U,0xE000U,0xE008U,0xE010U,0xE01FU,0xF000U
#define bbCPGUNICODE_BLOCKINDEX_OOB0 0x100000UL
#define bbCPGUNICODE_BLOCKINDEX_OOB1 0x110000UL
#define bbCPGUNICODE_BLOCKINDEX_OOBCOUNT 2

#define bbCPGUNICODE_BLOCKMASK 0xFFFEFFFFUL,0xFFF7DFFFUL,0xF77BFFFFUL,0xFFF55FFFUL,0x55D5DB7FUL,0x00000055UL
